export interface Personality {
  name: string;
  nameCN: string;
  quote: string;
  quoteCN: string;
  description: string;
  descriptionCN: string;
  image: string;
  axes: { E: number; S: number; M: number; V: number };
}

export const personalities: Record<string, Personality> = {
  STAR: {
    name: "STAR",
    nameCN: "主角症候群",
    quote: "The universe is a poorly funded indie film, and I'm the only A-lister on set.",
    quoteCN: "整个世界都是我的草台班子，而我是唯一的常驻嘉宾。",
    description: "You wake up every day and choose main character energy. You hustle, you glow, and you are proudly delulu enough to turn a grocery run into a cinematic masterpiece. Sure, your dramatic flair might make people roll their eyes, but your raw, unapologetic \"I'm the IT girl/boy\" vitality is honestly iconic. You magnificent, exhausting star—never let anyone dim your premium lighting. The world would be unbearably boring without you.",
    descriptionCN: "活脱脱的行走的聚光灯。你努力、你发光、你盲目自信，硬生生把平庸的日常过成了奥斯卡提名纪录片。虽然有时候你那强行加戏的做派让人想翻白眼，但你身上那种"老娘/老子天下第一"的生命力真的该死的迷人。你这迷人的小疯子，这个世界要是没你，还真挺无聊的。继续闪耀吧，毕竟主角是听不见路人甲叹气的！",
    image: "/assets/personalities/STAR.jpg",
    axes: { E: 0.8, S: 0.9, M: 0.8, V: 0.9 },
  },
  STAN: {
    name: "STAN",
    nameCN: "热衷粉",
    quote: "I will take a bullet for my bestie, but I need to mentally prepare to order a pizza.",
    quoteCN: "我可以替我闺蜜挡子弹，但我自己点个外卖都需要做半小时心理建设。",
    description: "The ultimate ride-or-die. You channel all your hustle, glow, and romantic filters into hyping up literally everyone but yourself. If your bestie or bias needs defense, you're throwing hands; if you need help, you apologize for existing. You think you're just the supporting cast, but your fierce, unapologetic loyalty is the absolute glue holding your circle together. You absolute gem, when are you going to start stanning yourself?",
    descriptionCN: "纯爱战神，最强辅助。你把所有的拼劲和滤镜全加在了别人身上。朋友或爱豆有难，你重拳出击；自己有事，你唯唯诺诺。你总觉得光环是别人的，但其实你那毫无保留的真诚和热烈，才是朋友圈里最珍贵的宝藏。你这个让人心疼又让人爱死的顶级捧哏，什么时候能把你那可怕的行动力用在自己身上，给自己也拉个横幅？",
    image: "/assets/personalities/STAN.jpg",
    axes: { E: 0.8, S: 0.7, M: 0.7, V: -0.7 },
  },
  HELP: {
    name: "HELP",
    nameCN: "崩溃者",
    quote: "I'm having a severe mental breakdown, but make it ✨aesthetic✨.",
    quoteCN: "只要我发疯发得够优雅，就没有人能看出我想死。",
    description: "You are a high-functioning disaster. You see the world for the burning trash fire it is, yet you still put on a full face of makeup to go fix it. You've somehow weaponized your own burnout, turning a mental breakdown into a breathtaking performance. You can literally cry your eyes out and then drop a flawless presentation. Honestly, your ability to slay while hanging by a thread is a terrifying superpower. Please schedule a nap.",
    descriptionCN: "表面控场女王/国王，内心碎成二维码。你看透了这破世界的本质，却依然卷起袖子一边骂街一边把活干得漂漂亮亮。你把崩溃演成了一门艺术，能在嚎啕大哭后立刻交出满分报告。说实话，你这种在废墟里还能蹦迪的强悍反差感，真是帅得让人嫉妒。你这个坚不可摧的疯批美人，请务必抽空心疼一下自己！",
    image: "/assets/personalities/HELP.jpg",
    axes: { E: 0.9, S: 0.8, M: -0.6, V: 0.7 },
  },
  BOSS: {
    name: "BOSS",
    nameCN: "卷者",
    quote: "I don't have a personality, I have a career. Just kidding, I only have back pain.",
    quoteCN: "我没有个性，但我有一份事业。骗你的，我也没事业，我只有颈椎病。",
    description: "Capitalism's favorite premium soldier. You see right through the corporate matrix, completely stripped of any delusions, yet you still reply \"Sounds great, thanks!\" at 11 PM with impeccable tone. You traded your social battery and ambitions for a paycheck. But let's not lie: navigating this dystopian survival game with such flawless, deadpan efficiency requires a monstrously high IQ. You ruthless corporate assassin, get your bag and get out.",
    descriptionCN: "资本主义最爱的顶级齿轮。你比谁都清醒，比谁都社畜，半夜三点还能带着完美的情绪价值回复老板消息。你把所有的野心和社交技巧都拿去换了工资，私下里却是个抽干了灵魂的空壳。但讲真，能把这么恶心的生存游戏玩得这么游刃有余，你的双商绝对是怪物级别的。你这可怕的职场杀神，赶紧搞钱然后提桶跑路吧！",
    image: "/assets/personalities/BOSS.jpg",
    axes: { E: 0.9, S: 0.6, M: -0.8, V: -0.7 },
  },
  CORE: {
    name: "CORE",
    nameCN: "装子",
    quote: "My life is falling apart, but my Instagram grid is healing.",
    quoteCN: "生活一团糟，但我的朋友圈必须高级。",
    description: "You are living in a meticulously curated Pinterest board. You hustle hard, but strictly to fund your pristine, highly delusional private universe. You avoid networking because actual human beings ruin your color palette. You'd rather eat ramen for a month than buy an ugly lamp. And honestly? Your aggressive commitment to the vibe absolutely saves you from the mundane. You stunning, untouchable artist—keep serving looks from your ivory tower.",
    descriptionCN: "活在精美滤镜里的高定玩家。你极其自律，但只为了维护你那个完美无瑕的"人设"和精神世界。你讨厌无用的社交，因为活人会破坏你的构图。你宁可忍受孤独，也要保持灵魂的高级感。不得不承认，你那该死的品味和对美的偏执，真的把你从庸俗中彻底拯救了出来。你这个迷人的高冷艺术家，就请继续独自美丽吧！",
    image: "/assets/personalities/CORE.jpg",
    axes: { E: 0.7, S: -0.6, M: 0.8, V: 0.8 },
  },
  CLWN: {
    name: "CLWN",
    nameCN: "小丑",
    quote: "I've rehearsed my Oscar speech 100 times for a movie I haven't been cast in.",
    quoteCN: "我已经排练了一百遍获奖感言，就等一个永远不会来的剧本。",
    description: "The clumsy, earnest dreamer. You grind in the shadows, avoid the spotlight, yet harbor a massive, delulu inner universe where your grand comeback is just around the corner. Even though you tend to fumble at the worst moments, turning your dramatic arc into a sitcom, your \"try again tomorrow\" resilience is ridiculously endearing in a cynical world. You lovable underdog, your weird magic is totally valid.",
    descriptionCN: "笨拙又真诚的逐梦者。你默默内卷，习惯性社恐，却在心里给自己加了一万层主角滤镜，坚信总有一天会逆袭。虽然你总是在关键时刻掉链子，把你的人生演成了滑稽喜剧，但你那种屡战屡败、屡败屡战的天真，在这个精明的世界里简直像大熊猫一样珍贵。你这招人疼的笨蛋，你的光芒早晚会被懂你的人看到的！",
    image: "/assets/personalities/CLWN.jpg",
    axes: { E: 0.7, S: -0.7, M: 0.8, V: -0.6 },
  },
  MESS: {
    name: "MESS",
    nameCN: "混乱者",
    quote: "Chaos is my personal brand.",
    quoteCN: "混乱就是我的个人品牌。",
    description: "A walking contradiction of dark academia and villain energy. You hustle hard but are profoundly cynical; you loathe small talk but emit an unignorable, magnetic aura. You've weaponized your inner turmoil, looking like a beautifully broken genius straight out of an indie thriller. People are intimidated by your brooding silence, but they can't look away. You dangerously alluring enigma, never lose your sharp edge.",
    descriptionCN: "迷人又危险的暗黑学霸。你极度拼命，却又极度厌世；你抗拒人群，却自带让人无法忽视的主角气场。你把拧巴和内耗变成了一种独特的性感，活像从悬疑小说里走出来的破碎感天才。别人不懂你为什么总在自我折磨，但只有你知道，这种不合群的清醒是你力量的来源。你这散发着危险气息的疯批，请继续保持你的神秘感。",
    image: "/assets/personalities/MESS.jpg",
    axes: { E: 0.8, S: -0.8, M: -0.7, V: 0.7 },
  },
  QUIT: {
    name: "QUIT",
    nameCN: "退出者",
    quote: "Physically here, mentally touching grass in 2035.",
    quoteCN: "人在岗，心在 2035 年的沙滩。",
    description: "The absolute zenith of energy efficiency. You execute your tasks flawlessly and vanish like a ghost, refusing to offer a single ounce of unpaid emotional labor. You see right through the societal BS, stripped of all delusions and main character syndrome, leaving only raw survival instincts. Mastering the art of being unbothered to this chilling degree makes you look like an untraceable, top-tier assassin. Teach us your ways.",
    descriptionCN: "人类高效节能的巅峰之作。你尽职尽责地完成所有事，然后像一阵风一样消失，绝不附赠哪怕一秒钟的情绪价值。你看透了这世界的无聊，剥离了所有的滤镜和社交伪装，只留下纯粹的生存本能。讲真，能把"不争不抢"做到这种冷酷又极致的地步，你简直酷得像个没有任何弱点的顶级杀手。教教我吧，你是怎么做到如此无动于衷的？",
    image: "/assets/personalities/QUIT.jpg",
    axes: { E: 0.6, S: -0.8, M: -0.8, V: -0.8 },
  },
  SLAY: {
    name: "SLAY",
    nameCN: "躺赢者",
    quote: "Zero productivity, 100% vibes.",
    quoteCN: "生产力为零，但气场必须满分。",
    description: "The effortless icon. You do absolutely zero heavy lifting, yet you dominate the social scene with terrifying charisma. Armed with aggressive delusion and impenetrable confidence, you turn an average hand into a royal flush. You believe you are the center of the universe—and infuriatingly, the universe usually agrees. Your ability to never stress and still have everyone obsessed with your vibe is a maddeningly elite superpower. Keep slaying, royalty.",
    descriptionCN: "天生的万人迷。你把"毫不费力"刻进了骨子里，不用拼命也能在社交场上如鱼得水。你靠着强大的滤镜和无敌的自信，硬是把一手平庸的牌打成了王炸。你深信自己就是宇宙中心，而最气人的是，大家还真就吃你这一套。你这种不仅能放过自己，还能顺便让别人膜拜的松弛感，真是让人嫉妒得牙痒痒！继续闪耀吧，天生的赢家。",
    image: "/assets/personalities/SLAY.jpg",
    axes: { E: -0.8, S: 0.9, M: 0.8, V: 0.9 },
  },
  DELU: {
    name: "DELU",
    nameCN: "做梦者",
    quote: "Delulu is not just the solulu, it's my entire financial plan.",
    quoteCN: "妄想是我唯一的理财计划。",
    description: "The grandmaster of mental gymnastics. You might be rotting in bed physically, but in your mind, you are thriving. You skip the hard work and rely strictly on high-speed scrolling, manifesting, and rewriting reality to harvest joy. Your \"the universe will fix it\" logic is unhinged, but honestly? It is an invincible shield against real-world burnout. You joyful dream-weaver, your inner peace is legendary.",
    descriptionCN: "精神胜利法的集大成者。你对现实生活重拳出击，但在自己的精神世界里风生水起。你不卷、不争，只靠高强度冲浪和脑补就能获得最高级别的快乐。你那套"一切都是宇宙最好安排"的逻辑，虽然听起来离谱，但不得不说，这绝对是你屏蔽内耗的最强护盾。你这快乐的造梦师，能把日子过得这么自洽，本身就是一种了不起的超能力！",
    image: "/assets/personalities/DELU.jpg",
    axes: { E: -0.7, S: 0.8, M: 0.9, V: -0.6 },
  },
  BRAT: {
    name: "BRAT",
    nameCN: "反骨者",
    quote: "I didn't come to fit in, I came to make it everybody's problem.",
    quoteCN: "我不是来融入你们的，我是来给你们添堵的。",
    description: "The chaotic neutral gremlin we love to hate. You see the world's hypocrisy, refuse to play the game, and respond with pure, unadulterated snark. You are lazy, brutally honest, and armed with an absurd amount of unearned confidence. You are the menace who ruins the peace but makes the group chat 100x funnier. If you weren't around, everything would be unbearably boring. Never stop being a problem.",
    descriptionCN: "让人又爱又恨的混世魔王。你看透了这虚伪的世界，并且决定用"发疯"来拆穿它。你懒散、毒舌，从不掩饰自己的粗糙，却带着一种狂野的主角魅力。你就像那个永远在课堂上接茬的坏学生，虽然经常气得人肝疼，但要是哪天你不在，这局绝对毫无乐趣可言。你这个让人上瘾的麻烦精，请继续保持你的无理取闹！",
    image: "/assets/personalities/BRAT.jpg",
    axes: { E: -0.7, S: 0.8, M: -0.8, V: 0.8 },
  },
  TRSH: {
    name: "TRSH",
    nameCN: "垃圾浣熊",
    quote: "I set the bar so low it's practically a tripping hazard in hell.",
    quoteCN: "我把底线设得很低，低到连地狱里的小鬼都会被绊一跤。",
    description: "The absolute ceiling of self-deprecating humor. You are brutally aware of your own uselessness, and instead of fixing it, you tweet about it for clout. You deconstruct all societal anxiety because when you're already laying flat, no one can knock you down. Your \"I'm garbage, what are you gonna do about it?\" defense mechanism is the ultimate antidote to modern hustle culture. We are obsessed with your flawless honesty.",
    descriptionCN: "自黑界的天花板。你极其清醒地知道自己有多废，不仅不改，还要大方地在网上开麦嘲笑自己。你用极其松弛的态度解构了所有的焦虑和期待——毕竟当一个人躺得足够平，就没人能割到你的韭菜。你那套"我已经这么烂了你还能拿我怎样"的防御机制，简直是当代年轻人的精神解药。你这个人间清醒的开心果，谁能拒绝一个坦诚的废柴呢？",
    image: "/assets/personalities/TRSH.jpg",
    axes: { E: -0.8, S: 0.7, M: -0.8, V: -0.7 },
  },
  POET: {
    name: "POET",
    nameCN: "湿人",
    quote: "I'm not ghosting you, I'm just romanticizing my isolation.",
    quoteCN: "你们不懂我，这就是我与生俱来的高贵。",
    description: "The modern-day brooding visionary. You reject the hustle and ghost everyone, but your inner world is rich enough to fill a trilogy. You rebrand your procrastination as \"creative incubation\" and wear your isolation like a crown of misunderstood genius. Even if you just post cryptic quotes at 3 AM, your refusal to conform to a basic lifestyle is incredibly intriguing. You lovely, lonely artist, please touch grass occasionally.",
    descriptionCN: "赛博时代的林黛玉。你拒绝内卷，极度社恐，但你的精神世界丰富得能写出一部巨著。你把拖延症包装成艺术家的沉淀，给自己套上了八百层"怀才不遇"的主角滤镜。虽然你经常在深夜无病呻吟，但你内心那份不肯向平庸妥协的孤傲，在这个快餐时代真的非常迷人。你这惹人怜爱的孤独天才，记得偶尔下凡呼吸点新鲜空气！",
    image: "/assets/personalities/POET.jpg",
    axes: { E: -0.7, S: -0.8, M: 0.8, V: 0.7 },
  },
  CAPY: {
    name: "CAPY",
    nameCN: "划水者",
    quote: "The world is literally burning, but I am cozy and well-hydrated.",
    quoteCN: "天塌下来有高个子顶着，我连头都懒得抬。",
    description: "The zen master of the apocalypse. You don't hustle, you don't mingle, you don't romanticize, and you definitely don't doomscroll. Society is collapsing, and you're just chilling in your lane. You figured out the ultimate hack: zero expectations equals zero disappointment. Your ability to remain completely unbothered in a manic world is an insanely enviable, god-tier trait. You majestic capybara, stay cozy.",
    descriptionCN: "精神状态最稳定的活佛。你不拼命、不社交、不抱幻想也从不悲观。外面天崩地裂，你依然在自己的小角落里安详地喝着奶茶。你没有宏大的叙事，却掌握了宇宙最强的生存法则：不期待就不会失望，不争抢就永远不输。你这只情绪绝对绝缘的终极水豚，能在这个癫狂的世界里稳如老狗，绝对是让人极度羡慕的神仙体质！",
    image: "/assets/personalities/CAPY.jpg",
    axes: { E: -0.8, S: -0.7, M: 0.7, V: -0.8 },
  },
  VILN: {
    name: "VILN",
    nameCN: "厌世者",
    quote: "I could easily destroy my enemies, but my bed is simply too comfortable today.",
    quoteCN: "拯救世界太累了，我还是在家里看着它毁灭吧。",
    description: "The cynical genius who logged off. You have the razor-sharp intellect to see through everyone's BS, but because humans are exhausting, you just opted out of the game. You carry heavy \"dark protagonist\" lore, and while you avoid people, when you do speak, it's a lethal, unapologetic roast. Your \"I could dominate, but I literally don't care\" vibe is unfathomably cool. Thank god you chose napping over world domination.",
    descriptionCN: "智商溢出的厌世王者。你拥有看穿一切虚伪的锐利目光，但因为觉得人类太蠢，连骂他们都嫌费力，索性直接躺平。你带着浓浓的黑暗主角光环，虽然社恐且佛系，但只要你一张口，必定是一针见血的绝杀。你这种"明明可以赢，但我懒得玩"的高傲感，简直酷到没朋友。你这深藏不露的大魔王，真庆幸你选择了睡觉而不是毁灭地球。",
    image: "/assets/personalities/VILN.jpg",
    axes: { E: -0.8, S: -0.9, M: -0.8, V: 0.8 },
  },
  PLNT: {
    name: "PLNT",
    nameCN: "草者",
    quote: "Please do not perceive me. I am merely background foliage.",
    quoteCN: "请不要注视我。我只是背景板里的一颗草。",
    description: "The absolute peak of minimalist survival. No hustle, no socializing, no delusions, and zero main character complex. You fully embrace being an extra. You are literally a houseplant—give you a dark corner and some Wi-Fi, and you will peacefully exist into the next century. Successfully lowering your desires and presence to this level makes you the ultimate anti-burnout icon. You cute, unproblematic foliage, nobody can disrupt your peace.",
    descriptionCN: "极简生存主义的最高境界。你不努力、不社交、不发梦、也不觉得自己是个人物，你完全接受了自己是个路人甲的设定。你就像一盆摆在角落的植物，只要有一口 Wi-Fi 就能安详地活到下个世纪。能把欲望和存在感降到这个地步，你简直是反内耗的终极标杆！你这盆可爱的植物，就这样安安静静地岁月静好吧，谁也别想吵醒你。",
    image: "/assets/personalities/PLNT.jpg",
    axes: { E: -0.9, S: -0.9, M: -0.9, V: -0.9 },
  },
};
